### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by travisdneel** [pilotak/docker-lirc-watcher#1]
Hi. Thanks for this project! It's made integrating my USB-UIRT, Broadlink and Harmony Remote integration into Home Assistant much better.

I am having an issue with high CPU usage though. 

I am running on Ubuntu 20.04 server through Docker. I got lirc installed and working with my Harmony 650 remote. I got MQTT installed and accessible with Home Assistant. I installed this with docker-compose and it works just like I need it to.

When this container is running, my CPU usage is around 30% and temperature around 50° C. If I stop the container, it goes down to about 16% CPU and 34° C.

I just installed the Glances docker container, and under the docker section, it shows this lirc container at using about 98 % CPU% and in the Tasks section, it shows python3 using 99 - 100.1% CPU%. Stopping the container removes both of these entries from Glances.

Any thoughts on what's causing this?

Here is my docker-compose.yml file for docker-lirc-watcher

```
version: "3"
services:
  lirc:
    container_name: lirc
    restart: always
    image: pilotak/lirc-watcher
    environment:
      - MQTT_BROKER=192.168.1.134
    volumes:
      - /var/run/lirc/lircd:/var/run/lirc/lircd
```
